"""fix markdown rendering of comments

Revision ID: b07ebb5fe6e0
Revises: 05eba44a406a
Create Date: 2023-02-14 12:10:39.167705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07ebb5fe6e0'
down_revision = '05eba44a406a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
